### ISSUE TITLE
Image thumbnails no longer visible in 'insert file' dialog due to missing return statement

### ISSUE THREAD

**Issue by hostep** [augustash/ash_pdfuploadaftersupee9767#1]
Hi

I just tested this plugin, seems to work perfectly fine, except for one major problem.
We no longer see the thumbnails of the images in the 'insert file' dialog.

This happens because this line: https://github.com/augustash/ash_pdfuploadaftersupee9767/blob/cf92279/app/code/community/Ash/PdfUploadAfterSupee9767/Model/Rewrite/Cms/Wysiwyg/Images/Storage.php#L37 needs to have a return statement, because that function should return the filepath of the thumbnail image.
(tested on a fully patched Magento CE 1.9.0.1 installation btw)

Thanks for the module!

**Comment by jakilcz** [comment]
yep, like stated ago, changing this line to
            return parent::resizeFile($source, $keepRation);

solves the problem.

**Comment by grafikchaos** [comment]
Thanks @hostep and @jakilcz for reporting the issue and proposing the confirmed solutions. Sorry it took that long to fix it.
